#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

alias mach_java_mode="export SDKMAN_DIR="$HOME/.sdkman" && [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh""

# ls
alias l="ls -la"
alias ll="ls -l"

# git
alias gaa="git add ."
alias gcam="git commit -m "

# weird
alias nihao="cowsay nihao"

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac

if [[ -d /opt/CIC ]]; then
    alias cic_mount='
      sudo mount -t nfs CASGPU:VOL1/Shared/CIC /opt/CIC -o ro
    '
else
    alias cic_mount='
      sudo mount -t nfs CASGPU:VOL1/Shared/CIC /opt/CIC -o ro
      sudo mkdir -p /usr/cad/CBDK
      sudo ln -s /opt/CIC/Cell_Libraries/CBDK018_UMC_Faraday_v1.0 /usr/cad/CBDK
      sudo ln -s /opt/CIC/Cell_Libraries/CBDK_IC_Contest_v2.1 /usr/cad/CBDK
      sudo ln -s /opt/CIC/Cell_Libraries/CBDK_IC_Contest_v2.5 /usr/cad/CBDK
    '
fi

alias cic_start='
    # source /opt/CIC/exec/vcs.shrc
    source /opt/CIC/exec/Verdi.shrc
    source /opt/CIC/exec/Synthesis.shrc
    source /opt/CIC/exec/IES.shrc
    source /opt/CIC/exec/Jasper.shrc
    source /opt/CIC/exec/Innovus.shrc
    source /opt/CIC/exec/Primetime.shrc
'

alias cic_stop='unset LD_LIBRARY_PATH'
