#!/bin/sh
# The script uses zap as plugin manager

# plugins
plug "zap-zsh/supercharge"
plug "zap-zsh/completions"
plug "zap-zsh/sudo"
plug "zap-zsh/nvm"
plug "zap-zsh/fzf"
plug "Aloxaf/fzf-tab"
plug "hlissner/zsh-autopair"
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"

# prompt
plug "zap-zsh/atmachine-prompt"
